cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
  path('add/<uuid:food_id>/', views.add_cart, name='add_cart'),
  path('', views.cart_detail, name='cart_detail'),
  path('remove/<uuid:food_id>/', views.cart_remove, name='cart_remove'),
  path('full_remove/<uuid:food_id>/', views.full_remove, name='full_remove'), 
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.orderDetail.as_view(), name='order_detail'),
    path('thanks/', views.thank_you, name='thank_you'), # url to appear after review submission
    path('<int:order_id>/feedback/', views.submit_feedback, name='submit_feedback'),
    # path('feedbacks/', views.feedback_list, name='feedback_list'),
    path('feedbacks/', views.latest_feedbacks, name='latest_feedbacks'),
]

restaurant/urls.py
from django.urls import path, include
from .import views
from .views import FoodCreateView 

app_name = 'restaurant'

urlpatterns = [
    path('', views.food_list, name = 'all_foods'),
    path('order/', include('order.urls')),
    path('<uuid:category_id>/', views.food_list, name = 'foods_by_category'),
    path('<uuid:category_id>/<uuid:food_id>/', views.food_detail, name = 'food_detail'),
    path('new/', FoodCreateView.as_view(), name='food_create'),
]

restaurantproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('restaurant.urls')),
    path('search/', include('search.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('passwordchange/', include('passwordchange.urls')),
    path('reservation/', include('reservation.urls')),
    path('contactform/', include('contactform.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from vouchers.models import Voucher
from django.utils import timezone

class Order(models.Model):
    token = models.CharField(max_length=250, blank=True)
    total = models.DecimalField(max_digits=10, decimal_places=2,
verbose_name='Euro Order Total')
    emailAddress = models.EmailField(max_length=250, blank=True,
verbose_name='Email Address')
    created = models.DateTimeField(auto_now_add=True)
    billingName = models.CharField(max_length=250, blank=True)
    billingAddress1 = models.CharField(max_length=250, blank=True)
    billingCity = models.CharField(max_length=250, blank=True)
    billingPostcode = models.CharField(max_length=10, blank=True)
    billingCountry = models.CharField(max_length=200, blank=True)
    shippingName = models.CharField(max_length=250, blank=True)
    shippingAddress1 = models.CharField(max_length=250, blank=True)
    shippingCity = models.CharField(max_length=250, blank=True)
    shippingPostcode = models.CharField(max_length=10, blank=True)
    shippingCountry = models.CharField(max_length=200, blank=True)
    voucher = models.ForeignKey(Voucher,
                                related_name='orders',
                                null=True,
                                blank=True,
                                on_delete=models.SET_NULL)
    discount = models.IntegerField(default = 0,
                                validators=[MinValueValidator(0),
                                MaxValueValidator(100)]) 

    class Meta:
        db_table = 'Order'
        ordering = ['-created']

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    food = models.CharField(max_length=250)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2,
verbose_name='Euro Price')
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    class Meta:
        db_table = 'OrderItem'

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.food

# reviews
class Feedback(models.Model):
    customer_name = models.CharField(max_length=100, blank=True, null=True)    
    feedback_text = models.TextField()
    rating = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.customer_name:
            return f"{self.customer_name} | {self.rating}/5"
        else:
            return f"Anonymous | {self.rating}/5"

order/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['customer_name', 'feedback_text', 'rating']
        widgets = {
            'rating': forms.Select(choices=[(i, str(i)) for i in range(1, 6)])  # Dropdown menu with choices 1 to 5
        }

order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import FeedbackForm
from .models import Order, OrderItem, Feedback
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

def thanks(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)
    return render(request, 'thanks.html',{'customer_order': customer_order})
    
# reviews
def submit_feedback(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.order = order
            feedback.save()
            return redirect('order:thank_you')
    else:
        form = FeedbackForm()
    return render(request, 'order/feedback_form.html', {'form': form})

def thank_you(request):
    return render(request, 'thank_you.html')

def latest_feedbacks(request):
    latest_feedbacks = Feedback.objects.order_by('-timestamp')[:5]
    return render(request, 'latest_reviews.html', {'latest_feedbacks': latest_feedbacks})

class orderHistory(LoginRequiredMixin, View):
    def get (self, request):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order_details = Order.objects.filter(emailAddress=email)
        return render(request, 'order/orders_list.html', {'order_details': order_details})

class orderDetail(LoginRequiredMixin, View):
    def get(self, request, order_id):
        if request.user.is_authenticated:
            email = str(request.user.email)
            order = Order.objects.get(id=order_id, emailAddress=email)
            order_items = OrderItem.objects.filter(order=order)

        return render(request, 'order/order_detail.html', {'order': order, 'order_items': order_items})   
          

order/templates/order/feedback_form.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Post Review | Spice Garden
{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <br>
            <h1 class="text-center my_title">Post a Review</h1>
            <br>
            <form method="post" class="text-center">
                {% csrf_token %}
                <div class="form-group">
                    <label for="customer_name">Name:</label>
                    {{ form.customer_name }}
                </div>
                <br>
                <div class="form-group">
                    <label for="feedback_text">Review:</label>
                    {{ form.feedback_text }}
                </div>
                <br>
                <div class="form-group">
                    <label for="rating">Rating:</label>
                    {{ form.rating }}
                </div>
                <br>
                <div class="text-center">
                    <button class="btn btn-dark" type="submit">Submit</button>
                </div>
                <br>
            </form>
        </div>
    </div>
</div>
{% endblock %}

order/templates/order/feedback_list.html
{% extends "base.html" %}
{% block title %}
Feedback List | Spice Garden
{% endblock %}
{% block content %}
<div class="container">
  <h1>Feedback List</h1>
  <ul>
    {% for feedback in feedbacks %}
      <li>{{ feedback.customer_name }} - {{ feedback.rating }}</li>
      <li>{{ feedback.feedback_text }}</li>
      <li>{{ feedback.timestamp }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

order/templates/order/order_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Order Details | Spice Garden
{% endblock %}
{% block content %}
<div class="container">
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Order Details</h1>
        <br>
        <table class="table table-bordered">
            <tr>
                <td class="text-left" colspan="2">
                    <b>Order: </b>#{{ order.id }}<br>
                    <b>Date: </b>{{ order.created|date:"d M Y" }}<br>
                    <b>Order Total: </b>€{{ order.total }}<br>
                    <b>Order Status: </b><i class="fas fa-check"></i>
                </td>    
                <td class="text-left" colspan="2">
                    <b>Billing Address: </b><br>
                    {{ order.billingName }}<br>
                    {{ order.billingAddress1 }}<br>
                    {{ order.billingCity }}<br>
                    {{ order.billingCountry }}<br>
                </td>
            </tr>
            <tr>
                <td><b>Product Description</b></td>
                <td><b>Qty</b></td>
                <td><b>Unit Price</b></td>
                <td><b>Sub-Total</b></td>
            </tr>
            {% for item in order_items %}
            <tr>
                <td>{{ item.food }}</td>
                <td>{{ item.quantity }}</td>
                <td>€{{ item.price }}</td>
                <td>€{{ item.sub_total }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td class="text-right" colspan="3"><b>Total</b></td>
                <td>€{{ order.total }}</td>
            </tr>
            <tr>
                <td class="text-right" colspan="3"><b>Total Paid</b></td>
                <td>€{{ order.total }}</td>
            </tr>
            <tr>
                <td class="text-left" colspan="2">
                    <b>Shipping Address: </b><br>
                    {{ order.shippingName }}<br>
                    {{ order.shippingAddress1 }}<br>
                    {{ order.shippingCity }}<br>
                    {{ order.shippingCountry }}<br>
                </td>
                <td class="text-left" colspan="2">
                    <b>Payment Details: </b><br>
                    The order #{{ order.id }} has been paid successfully via Stripe.
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock content %}

order/templates/order/orders_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Order History | Spice Garden
{% endblock %}
{% block content %}
    <div class="container">
        <div class="text-center">
            <br>
            <h1 class="text-center my_title">Order History</h1>
            <br>
            {% if order_details %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Order Number</th>
                        <th>Order Date</th>
                        <th>Total Amount</th>
                        <th>Status</th>
                        <th>Action</th>
                        <th>Review</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in order_details %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.created|date:"d M Y" }}</td>
                        <td>{{ order.total }}</td>
                        <td><i class="fas fa-check"></i>&nbsp;Complete</td>
                        <td><a href="{% url 'order:order_detail' order.id %}">View order</a></td>
                        <td><a href="{% url 'order:submit_feedback' order.id %}">Post review</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>You have not placed any orders yet.<br><br><a href="{% url 'restaurant:all_foods' %}" 
                                                           class="btn btn-dark">Continue shopping</a></p>
            {% endif %}
        </div>
    </div>
    <br>
    <br>
{% endblock %}