cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
  path('add/<uuid:food_id>/', views.add_cart, name='add_cart'),
  path('', views.cart_detail, name='cart_detail'),
  path('remove/<uuid:food_id>/', views.cart_remove, name='cart_remove'),
  path('full_remove/<uuid:food_id>/', views.full_remove, name='full_remove'), 
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', views.orderDetail.as_view(), name='order_detail'),
    path('thanks/', views.thank_you, name='thank_you'), # url to appear after review submission
    path('<int:order_id>/feedback/', views.submit_feedback, name='submit_feedback'),
    # path('feedbacks/', views.feedback_list, name='feedback_list'),
    path('feedbacks/', views.latest_feedbacks, name='latest_feedbacks'),
]

restaurant/urls.py
from django.urls import path, include
from .import views
from .views import FoodCreateView 

app_name = 'restaurant'

urlpatterns = [
    path('', views.food_list, name = 'all_foods'),
    path('order/', include('order.urls')),
    path('<uuid:category_id>/', views.food_list, name = 'foods_by_category'),
    path('<uuid:category_id>/<uuid:food_id>/', views.food_detail, name = 'food_detail'),
    path('new/', FoodCreateView.as_view(), name='food_create'),
]

restaurantproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('restaurant.urls')),
    path('search/', include('search.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('passwordchange/', include('passwordchange.urls')),
    path('reservation/', include('reservation.urls')),
    path('contactform/', include('contactform.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult'),
]

restaurant/models.py
from django.db import models
import uuid
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('restaurant:foods_by_category', args=[self.id])

    def __str__(self):
        return self.name


class Food(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'food', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'food'
        verbose_name_plural = 'foods'

    def get_absolute_url(self):
        return reverse('restaurant:food_detail', args=[self.category.id, self.id])

    def __str__(self):
        return self.name

restaurant/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Food
from order.models import Feedback
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin


def food_list(request, category_id=None):
    category = None
    foods = Food.objects.filter(available=True)
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        foods = Food.objects.filter(category=category, available=True)

    paginator = Paginator(foods, 15)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        foods = paginator.page(page)
    except (EmptyPage, InvalidPage):
        foods = paginator.page(paginator.num_pages)

    return render(request, 'restaurant/category.html', {'category':category, 'foods':foods})    

def food_detail(request, category_id, food_id):
    food = get_object_or_404(Food, category_id=category_id, id=food_id)
    return render(request, 'restaurant/food.html', {'food':food})

# displayed when manager login to 'update menu'
class FoodCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'restaurant.add_food'
    model = Food
    fields = ('name', 'description', 'price', 'category','stock', 'image')
    template_name = 'restaurant/food_new.html' 

restaurant/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
    crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
            {% include 'top-navbar.html' %}
        </div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}

        {% include 'footer.html' %}
    </div>
        
        <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-
    geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>

</body>
</html> 

restaurant/templates/footer.html
<div class = "footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; Spice Garden. All Rights Reserved.</p>
</div>

restaurant/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <a href="{% url 'restaurant:all_foods' %}">
            <img class="logo_image" src="{% static 'images/Restaurant_management_Logo_resized.jpg' %}"
        alt=""></a>
    </div>
</header>

restaurant/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            ariacontrols="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurant:all_foods' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" ariaexpanded="false">
                        Menu
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'order:latest_feedbacks' %}">Reviews</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Cart</a>
                </li>
                {% if item_count > 0 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i
                        class="fas fa-shopping-cart">({{item_count}})</i></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reserve_table' %}">Reservation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'search:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search here.." aria-label="Search" name="q">
                <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

restaurant/templates/top-navbar.html
{% load auth_extras %}
<div class="container">
    <div class="my_custom_menu">
        <ul>
            {% if user.is_authenticated %}
            <li>
                Welcome, <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" 
                aria-haspopup="true" aria-expanded="false">{{ user.username }} 
                <i class="fas fa-user-circle"></i></a>
                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'edit_profile'%}" class="dropdown-item">Edit Profile</a>
                    <a href="{% url 'change_password'%}" class="dropdown-item">Change Password</a>
                    <a href="{% url 'order:order_history' %}" class="dropdown-item">Order History</a>
                    
                    {% if user|has_group:"Manager" %}
                        <a href="{% url 'restaurant:food_create'%}" class="dropdown-item">Update Menu</a>
                    {% endif %}
                </div>
            </li>
            <li>
                <a href="{% url 'logout' %}">Logout <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login <i class="fas fa-sign-in-alt"></i></a>
            </li>
        
            {% endif %}
        </ul>
        
    </div>
</div>